# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple sum
#' @param x a numeric vector
#' @export
calc_sum <- function(x) {
    .Call(`_VSCodeRcppDemo_calc_sum`, x)
}

